---
- name: Validate NGINX configuration
  ansible.builtin.command: /usr/sbin/nginx -t
  changed_when: false
  listen: Reload TMS NGINX

- name: Reload NGINX
  ansible.builtin.systemd_service:
    name: nginx
    state: reloaded
  listen: Reload TMS NGINX
